export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_POPUP_DATA = 'SET_POPUP_DATA'
export const SET_POSTS = 'SET_POSTS'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'